### PR TITLE
Add support for gerrit_canonical_web_url

### PR DESCRIPTION
**Pull request by palvarez89**

### CODE REVIEW

**Comment by mrlesmithjr** [comment]
@palvarez89 Can you also add this var to the `defaults/main.yml` and I will merge. Thanks for the contribution.

**Comment by palvarez89** [comment]
@mrlesmithjr Thanks for having a look at it. I wouldn't know what default value to use. Any suggestion? Something like `http://gerrit.example.org:8080` ?

Also, I guess that adding it to the README would be a good idea.

**Comment by mrlesmithjr** [comment]
@palvarez89 Yeah something around the default of the following would work as `pri_domain_name` is a defined var that I generally use.

`http://gerrit.{{ pri_domain_name }}:8080` would work. Yeah and the `README.md` would be a good idea to update.

Thanks for the work on this man.

**Comment by palvarez89** [comment]
After thinking a bit about the logic in `gerrit.config.j2` file, I think this is the best solution to add support for this.

I hope that it makes sense.

**Comment by mrlesmithjr** [comment]
@palvarez89 Looks good to me..Merged. And thanks for the contribution.

**Comment by palvarez89** [comment]
@mrlesmithjr You are welcome, thank you for sharing this role ;)

**Pull request merged**
